[project]
name = "skltemplate"
version = "0.1.0"
description = "A template for scikit-learn compatible packages."
authors = ["Vighnesh Birodkar <vighneshbirodkar@nyu.edu>", "Guillaume Lemaitre <g.lemaite58@gmail.com>"]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]
license = "BSD-3-Clause"
homepage = "https://github.com/scikit-learn-contrib/project-template"
readme = "README.md"

[dependencies]
python = "*"
scikit-learn = ">=1.4.2"

[pypi-dependencies]
skltemplate = { path=".", editable=true }

[feature.lint.dependencies]
# The version below should be aligned with the one of `.pre-commit-config.yaml`
black = "23.3.0"
ruff = "0.4.2"

[feature.lint.tasks]
black = { cmd = "black --check --diff skltemplate && black --check --diff examples" }
ruff = { cmd = "ruff check --output-format=full skltemplate && ruff check --output-format=full examples" }
lint = { depends_on = ["black", "ruff"]}

[feature.test.dependencies]
pytest = "*"
pytest-cov = "*"

[feature.test.tasks]
test = { cmd = "pytest -vsl --cov=skltemplate --cov-report=xml skltemplate" }

[feature.doc.dependencies]
matplotlib = "*"
numpydoc = "*"
pydata-sphinx-theme = "*"
sphinx = "*"
sphinx-gallery = "*"
sphinx-prompt = "*"

[feature.doc.tasks]
build-doc = { cmd = "make html", cwd = "doc" }
clean-doc = { cmd = "rm -rf _build", cwd = "doc" }

[environments]
doc = ["doc"]
lint = ["lint"]
test = ["test"]
